### ISSUE TITLE
ModuleNotFoundError: No module named 'get'

### ISSUE THREAD

**Issue by Super-dong94** [MLi-lab-Bioinformatics-NJUCM/HerbiV#14]
---------------------------------------------------------------------------
下面错误如何修改？
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[11], line 1
----> 1 from herbiv import analysis
      2 analysis.from_tcm_or_formula(['HVM0367', 'HVM1695'])

File D:\anaconda3\Lib\site-packages\herbiv\analysis.py:1
----> 1 import get
      2 import compute
      3 import output

ModuleNotFoundError: No module named 'get'

**Comment by Wesady** [comment]
抱歉，是打包时候的问题，把 D:\anaconda3\Lib\site-packages\herbiv\analysis.py的`import`改成`from . import`就可以，比如`from . import get`
